version: "3"
services:
  react-native:
    build: .
    privileged: true
    ports:
      - 8081:8081
    tty: true
    volumes:
      - ".:/home/react-native"
      - "node_modules:/home/react-native/node_modules"

volumes:
  node_modules: # ここでvolumeを定義
    driver: local
